[package]
name = "rust_landscape"
version = "0.1.0"
authors = ["Antonio Estévez <a.estevez.blanco@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7.3"
clap = "2.33.3"
regex = "1"

[lib]
name = "rust_landscape"
path = "src/lib.rs"

[[bin]]
name = "landscape_calculator"
path = "src/bin.rs"
